// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlmodel

import (
	"time"
)

type NewTask struct {
	Title       string  `json:"title"`
	Content     *string `json:"content"`
	IsCompleted *bool   `json:"is_completed"`
}

type NewUser struct {
	Name string `json:"name"`
}

type RSTask struct {
	ID          *string    `json:"ID"`
	Title       *string    `json:"title"`
	Content     *string    `json:"content"`
	IsCompleted *bool      `json:"is_completed"`
	CreatedAt   *time.Time `json:"created_at"`
	UpdatedAt   *time.Time `json:"updated_at"`
}

type RSUser struct {
	ID        *string    `json:"ID"`
	Name      *string    `json:"name"`
	LastSeen  *time.Time `json:"last_seen"`
	CreatedAt *time.Time `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

type TaskCreateResponse struct {
	IsSuccess bool      `json:"isSuccess"`
	Tasks     []*RSTask `json:"Tasks"`
	User      *RSUser   `json:"User"`
}

type UserCreateResponse struct {
	IsSuccess bool      `json:"isSuccess"`
	Users     []*RSUser `json:"Users"`
}
